WARNING  2021-02-22 21:10:54,602 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:11:14,679 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:11:25,493 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:11:30,236 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:26:52,182 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:27:09,716 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:27:25,253 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 21:27:46,289 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 22:55:51,672 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 22:55:54,764 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:01:26,684 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:01:29,887 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:03:06,625 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:03:10,391 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:03:42,878 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:04:05,931 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:19:21,577 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:19:24,425 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:19:35,641 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:20:03,305 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:56:43,222 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:56:46,348 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:57:01,777 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-22 23:57:07,715 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:03:41,569 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:03:45,858 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:04:02,235 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:04:09,271 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:05:53,999 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:05:57,027 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:06:14,103 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:06:22,525 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:09:02,407 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:09:05,491 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:09:23,426 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:09:31,065 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:14:31,931 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x000001AE648FEF88> and <tensorflow.python.keras.layers.wrappers.TimeDistributed object at 0x000001AE65A18CC8>).
WARNING  2021-02-23 00:14:31,952 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x000001AE65A2E0C8> and <tensorflow.python.keras.layers.merge.Concatenate object at 0x000001AE65AB5A48>).
WARNING  2021-02-23 00:14:31,953 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x000001AE65BA5888> and <tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x000001AE65A2E0C8>).
WARNING  2021-02-23 00:14:48,450 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:14:55,569 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:18:24,186 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000027BF89246C8> and <tensorflow.python.keras.layers.wrappers.TimeDistributed object at 0x0000027BF9A36408>).
WARNING  2021-02-23 00:18:24,214 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000027BF9A5F748> and <tensorflow.python.keras.layers.merge.Concatenate object at 0x0000027BF9ADBD48>).
WARNING  2021-02-23 00:18:24,214 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x0000027BF9B47088> and <tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000027BF9A5F748>).
WARNING  2021-02-23 00:18:33,939 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:18:37,344 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:19:14,153 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:19:40,915 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:26:01,146 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:26:04,149 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:26:19,352 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:26:53,388 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:42:03,945 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:42:07,140 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:42:27,116 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 00:42:55,456 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 01:03:52,274 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-23 01:03:55,846 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 19:58:36,749 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 19:58:41,971 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 19:59:02,480 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 19:59:46,446 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 20:40:01,224 Unresolved object in checkpoint: (root).optimizer.decay
WARNING  2021-02-25 20:40:01,224 Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING  2021-02-25 20:40:01,224 Unresolved object in checkpoint: (root).optimizer.momentum
WARNING  2021-02-25 20:40:01,224 Unresolved object in checkpoint: (root).optimizer.rho
WARNING  2021-02-25 20:40:01,224 Unresolved object in checkpoint: (root).optimizer.iter
WARNING  2021-02-25 20:40:01,224 A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING  2021-02-25 20:41:28,681 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 20:41:31,807 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 20:41:43,085 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 20:42:06,725 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 21:32:02,813 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-25 21:32:06,017 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 19:14:46,980 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 19:14:51,570 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 19:15:47,939 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 19:15:58,796 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 21:46:46,165 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-02-26 21:46:49,589 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:07:02,727 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:07:05,990 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:07:31,854 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:07:49,893 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:52:40,381 Unresolved object in checkpoint: (root).optimizer.decay
WARNING  2021-03-01 18:52:40,412 Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING  2021-03-01 18:52:40,412 Unresolved object in checkpoint: (root).optimizer.momentum
WARNING  2021-03-01 18:52:40,412 Unresolved object in checkpoint: (root).optimizer.rho
WARNING  2021-03-01 18:52:40,412 Unresolved object in checkpoint: (root).optimizer.iter
WARNING  2021-03-01 18:52:40,412 A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING  2021-03-01 18:55:02,926 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:55:06,208 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:55:26,862 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 18:55:54,862 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:25:48,640 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:25:52,673 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:31:02,063 Unresolved object in checkpoint: (root).optimizer.decay
WARNING  2021-03-01 20:31:02,079 Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING  2021-03-01 20:31:02,079 Unresolved object in checkpoint: (root).optimizer.momentum
WARNING  2021-03-01 20:31:02,079 Unresolved object in checkpoint: (root).optimizer.rho
WARNING  2021-03-01 20:31:02,079 Unresolved object in checkpoint: (root).optimizer.iter
WARNING  2021-03-01 20:31:02,079 A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING  2021-03-01 20:34:04,847 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:34:08,503 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:34:54,159 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 20:35:19,358 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 21:35:30,736 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.embeddings.Embedding object at 0x00000188F9E0C608> and <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x00000188FAF12D88>).
WARNING  2021-03-01 21:35:31,484 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x00000188F9E1ACC8> and <tensorflow.python.keras.layers.wrappers.TimeDistributed object at 0x00000188FAF203C8>).
WARNING  2021-03-01 21:35:31,485 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x00000188FB014048> and <tensorflow.python.keras.layers.core.RepeatVector object at 0x00000188FB022848>).
WARNING  2021-03-01 21:35:31,486 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.wrappers.TimeDistributed object at 0x00000188FAF203C8> and <tensorflow.python.keras.layers.merge.Concatenate object at 0x00000188FB0A4888>).
WARNING  2021-03-01 21:39:49,006 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 21:39:52,813 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 21:40:26,600 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 21:40:58,939 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 22:40:35,705 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 22:40:39,827 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 22:41:15,135 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-01 22:41:22,015 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:34:17,566 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:34:20,814 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:35:26,214 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:35:32,137 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:46:30,418 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:46:33,358 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:47:01,771 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 00:47:07,628 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 01:33:38,888 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 01:33:42,050 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 11:50:30,070 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 11:50:33,071 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 11:51:28,761 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-02 11:51:34,722 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:01:43,234 Model was constructed with shape (None, 150, 150, 3) for input Tensor("input_1:0", shape=(None, 150, 150, 3), dtype=float32), but it was called on an input with incompatible shape (None, 150, 3).
WARNING  2021-03-05 16:24:31,582 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:24:36,341 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:24:59,510 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:25:08,746 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:31:41,642 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000021406AA5BC8> and <tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000021406AEF748>).
WARNING  2021-03-05 16:31:41,644 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x000002140684C648> and <tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x00000214057CE448>).
WARNING  2021-03-05 16:31:41,645 Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.recurrent_v2.LSTM object at 0x0000021406AEF748> and <tensorflow.python.keras.layers.core.RepeatVector object at 0x0000021406B97908>).
WARNING  2021-03-05 16:33:52,635 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:33:56,497 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:34:13,402 Model was constructed with shape (None, 150, 150, 3) for input Tensor("input_1:0", shape=(None, 150, 150, 3), dtype=float32), but it was called on an input with incompatible shape (None, 20, 150, 150, 3).
WARNING  2021-03-05 16:39:36,906 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:39:41,576 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:39:52,780 Model was constructed with shape (None, 150, 150, 3) for input Tensor("input_1:0", shape=(None, 150, 150, 3), dtype=float32), but it was called on an input with incompatible shape (None, 20, 150, 150, 3).
WARNING  2021-03-05 16:40:42,944 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:40:47,569 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:41:31,475 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:41:37,827 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:42:49,492 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:42:58,916 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:49:10,913 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:49:13,867 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:50:25,329 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 16:50:32,655 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:19:32,652 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:19:35,847 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:20:10,609 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:20:16,871 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:57:22,111 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:57:25,002 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:57:39,472 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 17:57:45,290 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:43:46,934 Unresolved object in checkpoint: (root).optimizer.iter
WARNING  2021-03-05 18:43:46,934 Unresolved object in checkpoint: (root).optimizer.decay
WARNING  2021-03-05 18:43:46,934 Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING  2021-03-05 18:43:46,934 Unresolved object in checkpoint: (root).optimizer.momentum
WARNING  2021-03-05 18:43:46,934 Unresolved object in checkpoint: (root).optimizer.rho
WARNING  2021-03-05 18:43:46,934 A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING  2021-03-05 18:44:10,545 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:44:13,535 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:44:28,207 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:44:40,341 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:56:16,347 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:56:19,367 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:57:13,287 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-05 18:57:19,123 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 18:25:18,200 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 18:25:21,176 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 18:26:03,711 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 18:26:09,657 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 22:06:15,974 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 22:06:19,313 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-07 22:08:08,916 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 12:55:05,038 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 12:55:09,674 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 12:57:10,132 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 12:57:28,693 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 15:43:24,131 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video1820.mp4, 535680 bytes wanted but 0 bytes read,at frame 22/23, at time 11.00/11.05 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 15:43:27,124 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video2262.mp4, 691200 bytes wanted but 0 bytes read,at frame 23/24, at time 11.50/11.52 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 15:45:00,008 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video6188.mp4, 691200 bytes wanted but 0 bytes read,at frame 33/34, at time 16.50/16.51 sec. Using the last valid frame instead.
  UserWarning)

WARNING  2021-03-08 15:45:06,283 C:\Users\gad\Anaconda3\envs\ved2seq\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:130: UserWarning: Warning: in file data/videos/video8133.mp4, 691200 bytes wanted but 0 bytes read,at frame 29/30, at time 14.50/14.53 sec. Using the last valid frame instead.
  UserWarning)

